name: Project sync

on:
  issues:
    types: [opened, assigned]
  pull_request:
    types: [opened]

permissions: {}

jobs:
  sync:
    uses: ZirekHQ/.github/.github/workflows/project-sync.yml@04989cb0860429fc147a76f1dbcf4a3a63288960 # main
    secrets:
      PROJECT_SYNC_TOKEN: ${{ secrets.PROJECT_SYNC_TOKEN }}
